# Generated by Django 4.2.7 on 2024-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
