# Generated by Django 4.2.7 on 2024-02-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_followed_by_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_mod',
            field=models.DateTimeField(null=True),
        ),
    ]
