# Generated by Django 4.2.7 on 2024-02-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_last_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_mod',
        ),
    ]
