# Generated by Django 4.2.7 on 2024-02-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_post_last_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_mod',
            field=models.DateTimeField(null=True),
        ),
    ]
